name: mooReadAll
author: abidibo
category: Utilities
tags: [readall, expand, compress, cut, html, regexp, layer]
docs: http://www.abidibo.net/projects/js/mooReadAll
demo: http://www.abidibo.net/projects/js/mooReadAll/demo
current: 0.2
